//! Golden tests: check tokcost's hand-rolled `bpe::encode_ordinary` against
//! real tiktoken output.
//!
//! Fixtures live in `tests/fixtures/{cl100k,o200k}.fixtures`, one test case
//! per line as `<base64-encoded-utf8-text> <comma-separated-token-ids>`,
//! generated by `scripts/gen_golden_fixtures.py` (requires the real
//! `tiktoken` Python package — a dev-only tool, never a tokcost
//! dependency). Regenerate with:
//!
//! ```text
//! pip install tiktoken
//! python3 scripts/gen_golden_fixtures.py
//! ```

use tokcost::bpe::{self, Pattern};
use tokcost::vocab;

struct Case {
    text: String,
    expected: Vec<u32>,
}

fn b64_val(c: u8) -> Option<u8> {
    match c {
        b'A'..=b'Z' => Some(c - b'A'),
        b'a'..=b'z' => Some(c - b'a' + 26),
        b'0'..=b'9' => Some(c - b'0' + 52),
        b'+' => Some(62),
        b'/' => Some(63),
        _ => None,
    }
}

fn b64_decode(s: &str) -> Vec<u8> {
    let vals: Vec<u8> = s
        .bytes()
        .filter(|&c| c != b'=')
        .map(|c| b64_val(c).unwrap_or_else(|| panic!("invalid base64 byte {c:#x} in {s:?}")))
        .collect();

    let mut out = Vec::with_capacity(vals.len() * 3 / 4 + 3);
    for chunk in vals.chunks(4) {
        out.push((chunk[0] << 2) | chunk.get(1).map_or(0, |v| v >> 4));
        if let Some(&v2) = chunk.get(2) {
            out.push((chunk[1] << 4) | (v2 >> 2));
        }
        if let Some(&v3) = chunk.get(3) {
            out.push((chunk[2] << 6) | v3);
        }
    }
    out
}

fn parse_fixtures(raw: &str) -> Vec<Case> {
    raw.lines()
        .filter(|line| !line.is_empty())
        .map(|line| {
            let (b64, ids) = line
                .split_once(' ')
                .unwrap_or_else(|| panic!("malformed fixture line: {line:?}"));
            let text = String::from_utf8(b64_decode(b64))
                .unwrap_or_else(|e| panic!("fixture text isn't valid UTF-8: {e}"));
            let expected = if ids.is_empty() {
                Vec::new()
            } else {
                ids.split(',')
                    .map(|n| {
                        n.parse()
                            .unwrap_or_else(|e| panic!("bad token id {n:?}: {e}"))
                    })
                    .collect()
            };
            Case { text, expected }
        })
        .collect()
}

fn check_fixtures(raw: &'static str, pattern: Pattern) {
    let ranks = vocab::ranks_for(pattern);
    let cases = parse_fixtures(raw);
    assert!(!cases.is_empty(), "fixture file parsed to zero cases");

    let mut failures = Vec::new();
    for case in &cases {
        let actual = bpe::encode_ordinary(&case.text, ranks, pattern);
        if actual != case.expected {
            failures.push(format!(
                "text {:?}\n  expected: {:?}\n  actual:   {:?}",
                case.text, case.expected, actual
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{}/{} golden cases failed for {pattern:?}:\n\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n\n")
    );
}

#[test]
fn cl100k_matches_real_tiktoken() {
    check_fixtures(
        include_str!("fixtures/cl100k.fixtures"),
        Pattern::Cl100kBase,
    );
}

#[test]
fn o200k_matches_real_tiktoken() {
    check_fixtures(include_str!("fixtures/o200k.fixtures"), Pattern::O200kBase);
}
