//! Embedded tokenizer vocabularies and model -> tokenizer routing.
//!
//! The actual rank tables are generated by `build.rs` from the canonical
//! tiktoken files in `assets/` (see that file's doc comment for the format).
//! This module turns the generated blobs into `bpe::Ranks` on first use and
//! decides, given a model name, which tokenizer applies.

use crate::bpe::{Pattern, Rank, Ranks};
use std::sync::OnceLock;

include!(concat!(env!("OUT_DIR"), "/vocab_generated.rs"));

fn read_u32(bytes: &[u8], index: usize) -> u32 {
    let o = index * 4;
    u32::from_le_bytes([bytes[o], bytes[o + 1], bytes[o + 2], bytes[o + 3]])
}

/// Reconstruct each token's raw byte slice (index == rank) from the
/// generated blob + offsets table.
fn decode_tokens(blob: &'static [u8], offsets: &'static [u8], count: usize) -> Vec<&'static [u8]> {
    (0..count)
        .map(|i| {
            let start = read_u32(offsets, i) as usize;
            let end = read_u32(offsets, i + 1) as usize;
            &blob[start..end]
        })
        .collect()
}

fn build_ranks(tokens: &[&'static [u8]]) -> Ranks {
    let mut ranks = Ranks::with_capacity(tokens.len());
    for (rank, bytes) in tokens.iter().enumerate() {
        ranks.insert(bytes.to_vec(), rank as Rank);
    }
    ranks
}

static CL100K_RANKS: OnceLock<Ranks> = OnceLock::new();
static O200K_RANKS: OnceLock<Ranks> = OnceLock::new();

/// The rank table for `pattern`, built once and cached for the process
/// lifetime.
pub fn ranks_for(pattern: Pattern) -> &'static Ranks {
    match pattern {
        Pattern::Cl100kBase => CL100K_RANKS
            .get_or_init(|| build_ranks(&decode_tokens(CL100K_BLOB, CL100K_OFFSETS, CL100K_COUNT))),
        Pattern::O200kBase => O200K_RANKS
            .get_or_init(|| build_ranks(&decode_tokens(O200K_BLOB, O200K_OFFSETS, O200K_COUNT))),
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Tokenizer {
    /// An exact tiktoken-compatible BPE vocabulary.
    Bpe(Pattern),
    /// No public tokenizer exists for this model family; token counts are a
    /// calibrated heuristic, not an exact count.
    ClaudeEstimate,
}

/// A token count, tagged with whether it's exact (real BPE vocab) or a
/// heuristic estimate (Claude models — see `Tokenizer::ClaudeEstimate`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Count {
    Exact(usize),
    Estimated(usize),
}

impl Count {
    pub fn value(self) -> usize {
        match self {
            Count::Exact(n) | Count::Estimated(n) => n,
        }
    }

    pub fn is_estimated(self) -> bool {
        matches!(self, Count::Estimated(_))
    }
}

/// Model name prefixes that use `o200k_base` (GPT-4o and newer reasoning /
/// GPT families). Anything not matched here, and not a Claude model, is
/// assumed to be a `cl100k_base` model (gpt-3.5-turbo, gpt-4, gpt-4-32k,
/// text-embedding-ada-002, ...) — tiktoken's own default for unrecognized
/// OpenAI model names.
const O200K_PREFIXES: &[&str] = &[
    "gpt-4o",
    "chatgpt-4o",
    "gpt-4.1",
    "gpt-4.5",
    "gpt-5",
    "o1",
    "o3",
    "o4",
];

/// Decide which tokenizer a model name should use.
pub fn tokenizer_for_model(model: &str) -> Tokenizer {
    let model = model.to_ascii_lowercase();
    if model.starts_with("claude") {
        return Tokenizer::ClaudeEstimate;
    }
    if O200K_PREFIXES
        .iter()
        .any(|prefix| model.starts_with(prefix))
    {
        return Tokenizer::Bpe(Pattern::O200kBase);
    }
    Tokenizer::Bpe(Pattern::Cl100kBase)
}

/// Anthropic doesn't publish Claude's BPE vocabulary or merge rules, so
/// there is no way to count Claude tokens exactly outside their API. This
/// is a calibrated heuristic, not a tokenizer: Anthropic's own public
/// guidance puts a token at roughly 3.5 English characters, which this
/// mirrors. See the README's disclosure section.
fn estimate_claude_tokens(text: &str) -> usize {
    if text.is_empty() {
        return 0;
    }
    let chars = text.chars().count() as f64;
    (chars / 3.5).round().max(1.0) as usize
}

/// Count tokens in `text` for `model`, using an exact BPE vocab where one
/// exists and a disclosed estimate otherwise.
pub fn count(text: &str, model: &str) -> Count {
    match tokenizer_for_model(model) {
        Tokenizer::Bpe(pattern) => {
            let ranks = ranks_for(pattern);
            Count::Exact(crate::bpe::encode_ordinary(text, ranks, pattern).len())
        }
        Tokenizer::ClaudeEstimate => Count::Estimated(estimate_claude_tokens(text)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_counts_match_canonical_files() {
        assert_eq!(CL100K_COUNT, 100_256);
        assert_eq!(O200K_COUNT, 199_998);
    }

    #[test]
    fn every_single_byte_is_a_token_in_both_vocabs() {
        for pattern in [Pattern::Cl100kBase, Pattern::O200kBase] {
            let ranks = ranks_for(pattern);
            for b in 0u32..256 {
                assert!(
                    ranks.contains_key(&vec![b as u8]),
                    "{pattern:?} is missing single-byte token {b:#x}"
                );
            }
        }
    }

    #[test]
    fn ranks_for_is_cached_across_calls() {
        let a = ranks_for(Pattern::Cl100kBase) as *const Ranks;
        let b = ranks_for(Pattern::Cl100kBase) as *const Ranks;
        assert_eq!(a, b);
    }

    #[test]
    fn encode_ordinary_compresses_plain_english() {
        let ranks = ranks_for(Pattern::Cl100kBase);
        let tokens = crate::bpe::encode_ordinary("hello world", ranks, Pattern::Cl100kBase);
        assert!(!tokens.is_empty());
        assert!(tokens.len() < "hello world".len());
    }

    #[test]
    fn tokenizer_for_model_routes_known_families() {
        assert_eq!(
            tokenizer_for_model("gpt-3.5-turbo"),
            Tokenizer::Bpe(Pattern::Cl100kBase)
        );
        assert_eq!(
            tokenizer_for_model("gpt-4"),
            Tokenizer::Bpe(Pattern::Cl100kBase)
        );
        assert_eq!(
            tokenizer_for_model("gpt-4o-mini"),
            Tokenizer::Bpe(Pattern::O200kBase)
        );
        assert_eq!(
            tokenizer_for_model("o1-preview"),
            Tokenizer::Bpe(Pattern::O200kBase)
        );
        assert_eq!(
            tokenizer_for_model("claude-sonnet-5"),
            Tokenizer::ClaudeEstimate
        );
        assert_eq!(
            tokenizer_for_model("Claude-Opus-5"),
            Tokenizer::ClaudeEstimate
        );
    }

    #[test]
    fn count_tags_exact_vs_estimated() {
        let exact = count("hello world", "gpt-4o");
        assert!(matches!(exact, Count::Exact(_)));
        assert!(!exact.is_estimated());

        let estimated = count("hello world", "claude-sonnet-5");
        assert!(matches!(estimated, Count::Estimated(_)));
        assert!(estimated.is_estimated());
        assert_eq!(estimated.value(), 3); // 11 chars / 3.5 = 3.14, rounded
    }

    #[test]
    fn claude_estimate_of_empty_text_is_zero() {
        assert_eq!(count("", "claude-sonnet-5").value(), 0);
    }
}
